### ISSUE TITLE
[Question] Do you provide a pre-trained model?

### ISSUE THREAD

**Issue by jongphago** [lexisnexis-risk-open-source/ledetection#1]
Hello. Thanks for contributing to this wonderful project.

I have a question, 
Is the checkpoint(.pth) file required to run the image_demo.py file? If necessary, do you have a checkpoint file that you provide??

Thank you.

**Comment by vuptran** [comment]
Running `demo/image_demo.py` requires a pre-trained checkpoint. We will release our pre-trained models soon in the near future. In the meantime, you can download a pre-trained checkpoint from [MMDetection](https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb) and it should run with our `demo/image_demo.py` script, using the appropriate config file. Let us know how it goes.
